[workspace]
members = ["crates/core", "crates/native-gui", "crates/wasm"]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
repository = "https://github.com/Scaletta/PicoCover"
license = "CC-BY-NC-4.0"
readme = "README.md"